#include "hal_data.h"
#include "uart/bsp_uart.h"
#include "canfd/bsp_canfd0.h"
#include "canfd/bsp_canfd1.h"
#include "secure_modules/house_owner.h"
#include "SysTick/bsp_SysTick.h"
#include "secure_modules/encryption/encryption.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* 外部变量和函数声明 */
//extern volatile bool canfd0_rx_complete_flag;
//extern can_frame_t canfd0_tx_frame;
//extern can_frame_t canfd0_rx_frame;
//
//extern volatile bool canfd1_rx_complete_flag;
//extern can_frame_t canfd1_rx_frame;
//extern can_frame_t canfd1_tx_frame;
//
//extern volatile bool canfd0_senddata_enable;
//extern volatile bool canfd1_senddata_enable;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    /* 调试串口初始化 */
    Debug_UART4_Init(); // SCI4 UART 调试串口初始化
//    CANFD0_Init(); // CAN FD0 接口初始化
//    CANFD1_Init(); // CAN FD1 接口初始化
    SysTick_Init(100);
//    trustedhouse_init();

    printf("this is TrustZone Secure World!\r\n");

//    /* 加解密测试 */
//    printf("测试NS加解密功能：\r\n");
//    uint8_t m[] = "secret data2";
//    unsigned int mlen = strlen(m);
//    uint8_t *c = (uint8_t *)malloc(1024*sizeof(uint8_t));
//    unsigned long long *clen = (unsigned long long *)malloc(sizeof(unsigned long long));
//
//    printf("plain text(%d): %s\r\n", mlen, m);
//
//    printf("测试通过NS World的加密函数进行加密数据：\r\n");
//    printf("mlen = %d\r\n", mlen);
//    encrypt_data(c, clen, m, mlen);
//    printf("encrypted text:\r\n");
//
//    for(unsigned int i = 0; i < (*clen); i++)
//    {
//        printf("%02x", c[i]);
//    }
//    printf("\r\n");
//
//    uint8_t *dec_m = (uint8_t *)malloc(1024*sizeof(uint8_t));
//    unsigned long long *dec_mlen = (unsigned long long *)malloc(sizeof(unsigned long long));
//    printf("测试通过NS World的解密函数 解密数据：\r\n");
//    decrypt_data(dec_m, dec_mlen, c, *clen);
//    printf("decrypted text:\r\n");
//    for(unsigned int i = 0; i < (*dec_mlen); i++)
//    {
//        printf("%c", dec_m[i]);
//    }
//
//    printf("\r\n");

//    // 避免进入normal world 【仅用于开发测试】
//    while(1)
//    {
//        ;
//    }

//    printf("Trusted House Test!\r\n");
//    // trusted house 1
//    TrustedHouse th1 = trustedhouse_create();
//    if (th1.valid)
//    {
//        trustedhouse_enter(th1.housekeeper_id);
//    }
//
//    // trusted house 2
//    TrustedHouse th2 = trustedhouse_create();
//    if (th2.valid)
//    {
//        trustedhouse_enter(th2.housekeeper_id);
//    }
//
//    // trusted house 3
//    TrustedHouse th3 = trustedhouse_create();
//    if (th3.valid)
//    {
//        trustedhouse_enter(th3.housekeeper_id);
//    }
//
//
//    trustedhouse_destroy(th1.housekeeper_id);
//    trustedhouse_destroy(th2.housekeeper_id);
//    trustedhouse_destroy(th3.housekeeper_id);
//
//    while(1)
//    {
//        ;
//    }

//    printf("这是一个 CAN FD 通讯例程\r\n");
//    printf("打开串口助手发送以下指令，对 CAN-FD 进行相应的操作\r\n");
//    printf("\t指令   ------  操作\r\n");
//    printf("\t 0   ------  CAN-FD0 发送数据帧\r\n");
//    printf("\t 1   ------  CAN-FD1 发送数据帧\r\n");
//    printf("\t=======================================\r\n\r\n");
//
//    uint64_t frame_num = 1;
//
//    while(1)
//    {
//        if (true == canfd0_senddata_enable)
//        {
//            canfd0_senddata_enable = false; //清零标志位
//
//            /* 测试从 CANFD0 发送到 CANFD1 */
//            for(int i = frame_num; i > 0; i--)
//            {
//                CANFD0_Operation();
//            }
//
////            printf("等待 CANFD1 接收完成中断\r\n");
//            while (false == canfd1_rx_complete_flag);
//            canfd1_rx_complete_flag = false;
//
////            printf("CANFD0 -> CANFD1 开始验证数据\r\n");
//            for( uint16_t j = 0; j < canfd0_tx_frame.data_length_code; j++)
//            {
//                if (canfd0_tx_frame.data[j] != canfd1_rx_frame.data[j])
//                {
//                    printf("CANFD0发送数据与CANFD1接收数据不一致\r\n");
//                }
//            }
//            printf("CANFD0 -> CANFD1 测试完成\r\n\r\n");
//        }
//
//        if (true == canfd1_senddata_enable)
//        {
//            canfd1_senddata_enable = false; //清零标志位
//
//            /* 测试从 CANFD1 发送到 CANFD0 */
//            for(int i = frame_num; i > 0; i--)
//            {
//                CANFD1_Operation();
//            }
//
////            printf("等待 CANFD0 接收完成中断\r\n");
//            while (false == canfd0_rx_complete_flag);
//            canfd0_rx_complete_flag = false;
//
////            printf("CANFD1 -> CANFD0 开始验证数据\r\n");
//            for( uint16_t j = 0; j < canfd1_tx_frame.data_length_code; j++)
//            {
//                if (canfd1_tx_frame.data[j] != canfd0_rx_frame.data[j])
//                {
//                    printf("CANFD1发送数据与CANFD0接收数据不一致\r\n");
//                }
//            }
//            printf("CANFD1 -> CANFD0 测试完成\r\n\r\n");
//        }
//    }

//    printf("Secure World CAN FD 通讯测试完毕！\r\n");


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
