//#include "hal_data.h"
//#include "my_nsc_api.h"
//#include "uart/nsc_bsp_uart.h"
//
//FSP_CPP_HEADER
//void R_BSP_WarmStart(bsp_warm_start_event_t event);
//FSP_CPP_FOOTER
//
///*******************************************************************************************************************//**
// * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
// * is called by main() when no RTOS is used.
// **********************************************************************************************************************/
//void hal_entry(void)
//{
//    /* TODO: add your own code here */
//
//    // test an easy secure_add function NSC Call
//    My_nsc_api_Init(); //用户自定义api函数初始化
//    Debug_UART4_Init(); // SCI4 UART 调试串口初始化
//
//    printf("this is TrustZone_NS\r\n");
//    printf("这是一个简单例程:\r\n");
//    printf("进行一个加法运算,NS程序调用nsc_api, 使用Secure中的secure_add函数\r\n");
//
//    int a, b, c; // c=a+b
//    // 参数初始化
//    a = 1;
//    b = 2;
//    printf("num1 = %d, num2 = %d\r\n", a, b);
//    c = My_nsc_api_add(a, b);
//    printf("result is %d\r\n", c);
//
//    // test Ethernet communication in NS app
//
//#if BSP_TZ_SECURE_BUILD
//    /* Enter non-secure code */
//    R_BSP_NonSecureEnter();
//#endif
//}
//
///*******************************************************************************************************************//**
// * This function is called at various points during the startup process.  This implementation uses the event that is
// * called right before main() to set up the pins.
// *
// * @param[in]  event    Where at in the start up process the code is currently at
// **********************************************************************************************************************/
//void R_BSP_WarmStart(bsp_warm_start_event_t event)
//{
//    if (BSP_WARM_START_RESET == event)
//    {
//#if BSP_FEATURE_FLASH_LP_VERSION != 0
//
//        /* Enable reading from data flash. */
//        R_FACI_LP->DFLCTL = 1U;
//
//        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
//         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
//#endif
//    }
//
//    if (BSP_WARM_START_POST_C == event)
//    {
//        /* C runtime environment and system clocks are setup. */
//
//        /* Configure pins. */
//        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
//
//#if BSP_CFG_SDRAM_ENABLED
//
//        /* Setup SDRAM and initialize it. Must configure pins first. */
//        R_BSP_SdramInit(true);
//#endif
//    }
//}
//
//#if BSP_TZ_SECURE_BUILD
//
//FSP_CPP_HEADER
//BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();
//
///* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
//BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
//{
//
//}
//FSP_CPP_FOOTER
//
//#endif
